BaseUrl= "http://example.com/"
LanguageCode= "en-US"
Title= "Tôi là Dũng"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2019"
canonifyurls = true
theme = "robust"

# languageCode = "ja"
# title = "sin-tanaka.com"
#
# googleAnalytics = "UA-52059413-2" # Optional
# disqusShortname = "tanasinn"

[params]
  description = ""
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/avatar.jpg"
  avatar = "images/avatar.jpg"
  name = "Nguyễn Tiến Dũng"
  description = "<p>Tôi là một lập trình viên web, thích trồng cây và nhìn những hạt mầm nảy nở. Tôi thích sự mới mẻ và những thử thách làm cho cuộc sống luôn thú vị.</p>"
  facebook = "https://www.facebook.com/dungnguyen.ajt"
  # twitter = "https://twitter.com/_sin_tanaka"

[outputs]
page = [ "HTML"] # if you want AMP enable.